name: Cypress HTML Report

on:
  schedule:
    - cron: "0 0 * * 1"  # Ejecutar una vez a la semana, los lunes a la medianoche
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update npm
        run: npm install -g npm@latest

      - name: Remove existing dependencies
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and save logs to file
        run: npx cypress run 2>&1 | tee cypress-logs.txt || true

      - name: Generate Cypress HTML report from logs
        run: |
          # Tu código para generar el informe HTML aquí

      - name: Upload Cypress logs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-logs
          path: cypress-logs.txt

      - name: Upload Cypress HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-html-report
          path: cypress-report.html

      - name: Deploy Cypress HTML report to GitHub Pages
        run: |
          mkdir gh-pages
          mv cypress-report.html gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.BDD }}
