name: Cypress HTML Report

on:
  schedule:
    - cron: "0 0 * * 1"  # Ejecutar una vez a la semana, los lunes a la medianoche
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      # ... pasos anteriores

      - name: Generate Cypress HTML report from logs
        run: |
          echo "<!DOCTYPE html><html><head><style>
            body {
              font-family: Arial, sans-serif;
              margin: 20px;
              background-color: black;
              color: white;
            }
            pre {
              background-color: #333;
              padding: 10px;
              border: 1px solid #ddd;
              white-space: pre-wrap;
              font-size: 14px;
            }
            .passed {
              color: #00ff00;
            }
            .failed {
              color: #ff0000;
            }
            .skipped {
              color: #ffA500;
            }
            .summary {
              color: #00ff00;
            }
            .circle-container {
              display: flex;
              align-items: center;
              justify-content: center;
              height: 200px;
            }
            .circle {
              width: 100px;
              height: 100px;
              border-radius: 50%;
              background: transparent;
              position: relative;
              border: 3px solid white;
            }
            .sector.passed {
              background-color: #00ff00;
            }
            .sector.failed {
              background-color: #ff0000;
            }
            .sector.skipped {
              background-color: #ffA500;
            }
          </style></head><body><pre>" > cypress-report.html
          cat cypress-logs.txt | sed 's/\x1B\[[0-9;]*[JKmsu]//g' | sed -E 's/(✓[^<]*)/<span class="passed">\1<\/span>/g' >> cypress-report.html
          echo "</pre><span class='summary'>" >> cypress-report.html
          cat cypress-logs.txt | grep "All specs passed" >> cypress-report.html
          echo "</span><div class='circle-container'>
            <div class='circle'>
              <div class='sector passed'></div>
              <div class='sector failed'></div>
              <div class='sector skipped'></div>
            </div>
          </div></body></html>" >> cypress-report.html

      - name: Upload Cypress logs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-logs
          path: cypress-logs.txt

      - name: Upload Cypress HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-html-report
          path: cypress-report.html

      - name: Deploy Cypress HTML report to GitHub Pages
        run: |
          mkdir gh-pages
          mv cypress-report.html gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.BDD }}
